#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
CUR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
VER=$1
if [ -z "$VER" ]; then
	printf "%s\n" "Version argument must not be null"
	exit 1
fi
VERSION="$VER"
CVERSION="${VERSION//[.-]/_}"
printf "const char *NHARU_VERSION_%s = \"%s\";\n" "$CVERSION" "$VERSION">"$CUR/native/version.c"
printf "const char *NHARU_getVersion() { return NHARU_VERSION_%s; }" "$CVERSION">>"$CUR/native/version.c"

